namespace AfipWebServicesClient.Model
{
    // ReSharper disable UnusedMember.Global
    // ReSharper disable IdentifierTypo
    public enum TipoComprobante
    {
        FacturaA = 1,
        NotaDeDebitoA = 2,
        NotaDeCreditoA = 3,
        ReciboA = 4,
        NotaDeVentaAlContadoA = 5,
        FacturaB = 6,
        NotaDeDebitoB = 7,
        NotaDeCreditoB = 8,
        ReciboB = 9,
        NotaDeVentaAlContadoB = 10,
        FacturaC = 11,
        NotaDeDebitoC = 12,
        NotaDeCreditoC = 13,
        ReciboC = 15,
        FacturaDeExportacion = 19,
        NotaDebPOperacConElExterior = 20,
        NotaCredPOperacConElExterior = 21,
        FacPermExportSimpDto85597 = 22,
        CbtesCompraDeBienesUsados = 30,
        MandatoConsignacion = 31,
        ComprobantesDeCompraDeMaterialesAReciclarPr = 32,
        CbtesADelAnexoIApartadoAIncFrgNro1 = 34,
        CbtesBDelAnexoIApartadoAIncFrgNr = 35,
        NotaDebDocEquivQueCumplanConLaRgNro = 37,
        NotaCredDocEquivQueCumplanConLaRgNro = 38,
        OtrosComprobantesAQueCumplanConLaRgNro = 39,
        OtrosComprobantesBQueCumplanConLaRgNro = 40,
        FacturaM = 51,
        NotaDeDebitoM = 52,
        NotaDeCreditoM = 53,
        ReciboM = 54,
        NotaDeVentaAlContadoM = 55,
        ComprobantesMDelAnexoIApartadoAIncFr = 56,
        OtrosComprobantesMQueCumplanConLaRgNro = 57,
        CuentaDeVentaYLiquidoProductoM = 58,
        LiquidacionM = 59,
        CtaDeVtaYLiquidoProdA = 60,
        CtaDeVtaYLiquidoProdB = 61,
        LiquidacionA = 63,
        LiquidacionB = 64,
        ReciboDeFacturaDeCreditoR = 70,
        RemitoR = 91,
        ComprobanteDeCompraDeBienesUsados = 49,
        LiquidacionUnicaComercialImpositivaClaseA = 27,
        LiquidacionUnicaComercialImpositivaClaseB = 28,
        NotaDeCreditoLiquidacionUnicaComercialImpositivaClaseB = 43,
        NotaDeDebitoLiquidacionUnicaComercialImpositivaClaseA = 45,
        NotaDeDebitoLiquidacionUnicaComercialImpositivaClaseB = 46,
        NotaDeCreditoLiquidacionUnicaComercialImpositivaClaseA = 48,
        FacturaDeCreditoFcea = 201,
        NotaDeDebitoFcea = 202,
        NotaDeCreditoFcea = 203,
        FacturaDeCreditoFceb = 206,
        NotaDeDebitoFceb = 207,
        NotaDeCreditoFceb = 208,
        FacturaDeCreditoFcec = 211,
        NotaDeDebitoFcec = 212,
        NotaDeCreditoFcec = 213
    }
}