//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfipSire
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/")]
    public partial class certificado
    {
        
        private int versionField;
        
        private string codigoTrazabilidadField;
        
        private int impuestoField;
        
        private int regimenField;
        
        private System.DateTime fechaRetencionField;
        
        private int condicionField;
        
        private bool condicionFieldSpecified;
        
        private bool imposibilidadRetencionField;
        
        private string motivoNoRetencionField;
        
        private double importeRetencionField;
        
        private double importeBaseCalculoField;
        
        private bool regimenExclusionField;
        
        private double porcentajeExclusionField;
        
        private bool porcentajeExclusionFieldSpecified;
        
        private System.DateTime fechaPublicacionField;
        
        private bool fechaPublicacionFieldSpecified;
        
        private int tipoComprobanteField;
        
        private System.DateTime fechaComprobanteField;
        
        private string numeroComprobanteField;
        
        private string coeField;
        
        private string coeOriginalField;
        
        private string caeField;
        
        private double importeComprobanteField;
        
        private string motivoEmisionNotaCreditoField;
        
        private long cuitRetenidoField;
        
        private string numeroCertificadoOriginalField;
        
        private System.DateTime fechaRetencionCertificadoOriginalField;
        
        private bool fechaRetencionCertificadoOriginalFieldSpecified;
        
        private double importeCertificadoOriginalField;
        
        private bool importeCertificadoOriginalFieldSpecified;
        
        private int motivoAnulacionField;
        
        private bool motivoAnulacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoTrazabilidad
        {
            get
            {
                return this.codigoTrazabilidadField;
            }
            set
            {
                this.codigoTrazabilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int regimen
        {
            get
            {
                return this.regimenField;
            }
            set
            {
                this.regimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaRetencion
        {
            get
            {
                return this.fechaRetencionField;
            }
            set
            {
                this.fechaRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int condicion
        {
            get
            {
                return this.condicionField;
            }
            set
            {
                this.condicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool condicionSpecified
        {
            get
            {
                return this.condicionFieldSpecified;
            }
            set
            {
                this.condicionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool imposibilidadRetencion
        {
            get
            {
                return this.imposibilidadRetencionField;
            }
            set
            {
                this.imposibilidadRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string motivoNoRetencion
        {
            get
            {
                return this.motivoNoRetencionField;
            }
            set
            {
                this.motivoNoRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double importeRetencion
        {
            get
            {
                return this.importeRetencionField;
            }
            set
            {
                this.importeRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double importeBaseCalculo
        {
            get
            {
                return this.importeBaseCalculoField;
            }
            set
            {
                this.importeBaseCalculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool regimenExclusion
        {
            get
            {
                return this.regimenExclusionField;
            }
            set
            {
                this.regimenExclusionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double porcentajeExclusion
        {
            get
            {
                return this.porcentajeExclusionField;
            }
            set
            {
                this.porcentajeExclusionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porcentajeExclusionSpecified
        {
            get
            {
                return this.porcentajeExclusionFieldSpecified;
            }
            set
            {
                this.porcentajeExclusionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime fechaPublicacion
        {
            get
            {
                return this.fechaPublicacionField;
            }
            set
            {
                this.fechaPublicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPublicacionSpecified
        {
            get
            {
                return this.fechaPublicacionFieldSpecified;
            }
            set
            {
                this.fechaPublicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int tipoComprobante
        {
            get
            {
                return this.tipoComprobanteField;
            }
            set
            {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime fechaComprobante
        {
            get
            {
                return this.fechaComprobanteField;
            }
            set
            {
                this.fechaComprobanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string numeroComprobante
        {
            get
            {
                return this.numeroComprobanteField;
            }
            set
            {
                this.numeroComprobanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string coe
        {
            get
            {
                return this.coeField;
            }
            set
            {
                this.coeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string coeOriginal
        {
            get
            {
                return this.coeOriginalField;
            }
            set
            {
                this.coeOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string cae
        {
            get
            {
                return this.caeField;
            }
            set
            {
                this.caeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public double importeComprobante
        {
            get
            {
                return this.importeComprobanteField;
            }
            set
            {
                this.importeComprobanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string motivoEmisionNotaCredito
        {
            get
            {
                return this.motivoEmisionNotaCreditoField;
            }
            set
            {
                this.motivoEmisionNotaCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public long cuitRetenido
        {
            get
            {
                return this.cuitRetenidoField;
            }
            set
            {
                this.cuitRetenidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string numeroCertificadoOriginal
        {
            get
            {
                return this.numeroCertificadoOriginalField;
            }
            set
            {
                this.numeroCertificadoOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public System.DateTime fechaRetencionCertificadoOriginal
        {
            get
            {
                return this.fechaRetencionCertificadoOriginalField;
            }
            set
            {
                this.fechaRetencionCertificadoOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRetencionCertificadoOriginalSpecified
        {
            get
            {
                return this.fechaRetencionCertificadoOriginalFieldSpecified;
            }
            set
            {
                this.fechaRetencionCertificadoOriginalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public double importeCertificadoOriginal
        {
            get
            {
                return this.importeCertificadoOriginalField;
            }
            set
            {
                this.importeCertificadoOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeCertificadoOriginalSpecified
        {
            get
            {
                return this.importeCertificadoOriginalFieldSpecified;
            }
            set
            {
                this.importeCertificadoOriginalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int motivoAnulacion
        {
            get
            {
                return this.motivoAnulacionField;
            }
            set
            {
                this.motivoAnulacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motivoAnulacionSpecified
        {
            get
            {
                return this.motivoAnulacionFieldSpecified;
            }
            set
            {
                this.motivoAnulacionFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", ConfigurationName="AfipSire.C2005Soap")]
    public interface C2005Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AfipSire.dummyResponse> dummyAsync(AfipSire.dummy request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AfipSire.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AfipSire.emitirResponse> emitirAsync(AfipSire.emitir request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AfipSire.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AfipSire.anularResponse> anularAsync(AfipSire.anular request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.afip.gob.ar/sire/c2005/")]
    public partial class HeaderInfo
    {
        
        private string ambienteField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private string vCoreField;
        
        private string v2005Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ambiente
        {
            get
            {
                return this.ambienteField;
            }
            set
            {
                this.ambienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string vCore
        {
            get
            {
                return this.vCoreField;
            }
            set
            {
                this.vCoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string v2005
        {
            get
            {
                return this.v2005Field;
            }
            set
            {
                this.v2005Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dummy", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class dummy
    {
        
        public dummy()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dummyResponse", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class dummyResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/")]
        public AfipSire.HeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string appserver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string authserver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dbserver;
        
        public dummyResponse()
        {
        }
        
        public dummyResponse(AfipSire.HeaderInfo HeaderInfo, string appserver, string authserver, string dbserver)
        {
            this.HeaderInfo = HeaderInfo;
            this.appserver = appserver;
            this.authserver = authserver;
            this.dbserver = dbserver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="emitir", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class emitir
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitAgente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AfipSire.certificado certificado;
        
        public emitir()
        {
        }
        
        public emitir(string token, string sign, long cuitAgente, AfipSire.certificado certificado)
        {
            this.token = token;
            this.sign = sign;
            this.cuitAgente = cuitAgente;
            this.certificado = certificado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="emitirResponse", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class emitirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certificadoNro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSeguridad;
        
        public emitirResponse()
        {
        }
        
        public emitirResponse(string certificadoNro, string codigoSeguridad)
        {
            this.certificadoNro = certificadoNro;
            this.codigoSeguridad = codigoSeguridad;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/")]
    public partial class certificadoAnulacion
    {
        
        private int versionField;
        
        private string codigoTrazabilidadField;
        
        private int impuestoField;
        
        private string numeroCertificadoField;
        
        private int motivoAnulacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoTrazabilidad
        {
            get
            {
                return this.codigoTrazabilidadField;
            }
            set
            {
                this.codigoTrazabilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroCertificado
        {
            get
            {
                return this.numeroCertificadoField;
            }
            set
            {
                this.numeroCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int motivoAnulacion
        {
            get
            {
                return this.motivoAnulacionField;
            }
            set
            {
                this.motivoAnulacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anular", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class anular
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitAgente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AfipSire.certificadoAnulacion certificadoAnulacion;
        
        public anular()
        {
        }
        
        public anular(string token, string sign, long cuitAgente, AfipSire.certificadoAnulacion certificadoAnulacion)
        {
            this.token = token;
            this.sign = sign;
            this.cuitAgente = cuitAgente;
            this.certificadoAnulacion = certificadoAnulacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anularResponse", WrapperNamespace="http://www.afip.gob.ar/sire/c2005/", IsWrapped=true)]
    public partial class anularResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certificadoNro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.afip.gob.ar/sire/c2005/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSeguridad;
        
        public anularResponse()
        {
        }
        
        public anularResponse(string certificadoNro, string codigoSeguridad)
        {
            this.certificadoNro = certificadoNro;
            this.codigoSeguridad = codigoSeguridad;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface C2005SoapChannel : AfipSire.C2005Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class C2005SoapClient : System.ServiceModel.ClientBase<AfipSire.C2005Soap>, AfipSire.C2005Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public C2005SoapClient() : 
                base(C2005SoapClient.GetDefaultBinding(), C2005SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.C2005SoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public C2005SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(C2005SoapClient.GetBindingForEndpoint(endpointConfiguration), C2005SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public C2005SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(C2005SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public C2005SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(C2005SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public C2005SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AfipSire.dummyResponse> dummyAsync(AfipSire.dummy request)
        {
            return base.Channel.dummyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AfipSire.emitirResponse> emitirAsync(AfipSire.emitir request)
        {
            return base.Channel.emitirAsync(request);
        }
        
        public System.Threading.Tasks.Task<AfipSire.anularResponse> anularAsync(AfipSire.anular request)
        {
            return base.Channel.anularAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.C2005SoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.C2005SoapPort))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-aplicativos-reca.homo.afip.gob.ar/sire/ws/v1/c2005/2005");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return C2005SoapClient.GetBindingForEndpoint(EndpointConfiguration.C2005SoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return C2005SoapClient.GetEndpointAddress(EndpointConfiguration.C2005SoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            C2005SoapPort,
        }
    }
}
