//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfipConstanciaInscripcion;


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class SRValidationException
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class metadata
{
    
    private System.DateTime fechaHoraField;
    
    private bool fechaHoraFieldSpecified;
    
    private string servidorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public System.DateTime fechaHora
    {
        get
        {
            return this.fechaHoraField;
        }
        set
        {
            this.fechaHoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaHoraSpecified
    {
        get
        {
            return this.fechaHoraFieldSpecified;
        }
        set
        {
            this.fechaHoraFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string servidor
    {
        get
        {
            return this.servidorField;
        }
        set
        {
            this.servidorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class errorRegimenGeneral
{
    
    private string[] errorField;
    
    private string mensajeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public string[] error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string mensaje
    {
        get
        {
            return this.mensajeField;
        }
        set
        {
            this.mensajeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class errorMonotributo
{
    
    private string[] errorField;
    
    private string mensajeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public string[] error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string mensaje
    {
        get
        {
            return this.mensajeField;
        }
        set
        {
            this.mensajeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class errorConstancia
{
    
    private string apellidoField;
    
    private string[] errorField;
    
    private long idPersonaField;
    
    private bool idPersonaFieldSpecified;
    
    private string nombreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string apellido
    {
        get
        {
            return this.apellidoField;
        }
        set
        {
            this.apellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public string[] error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public long idPersona
    {
        get
        {
            return this.idPersonaField;
        }
        set
        {
            this.idPersonaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idPersonaSpecified
    {
        get
        {
            return this.idPersonaFieldSpecified;
        }
        set
        {
            this.idPersonaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string nombre
    {
        get
        {
            return this.nombreField;
        }
        set
        {
            this.nombreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class regimen
{
    
    private string descripcionRegimenField;
    
    private int idImpuestoField;
    
    private bool idImpuestoFieldSpecified;
    
    private int idRegimenField;
    
    private bool idRegimenFieldSpecified;
    
    private int periodoField;
    
    private bool periodoFieldSpecified;
    
    private string tipoRegimenField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string descripcionRegimen
    {
        get
        {
            return this.descripcionRegimenField;
        }
        set
        {
            this.descripcionRegimenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int idImpuesto
    {
        get
        {
            return this.idImpuestoField;
        }
        set
        {
            this.idImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idImpuestoSpecified
    {
        get
        {
            return this.idImpuestoFieldSpecified;
        }
        set
        {
            this.idImpuestoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int idRegimen
    {
        get
        {
            return this.idRegimenField;
        }
        set
        {
            this.idRegimenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idRegimenSpecified
    {
        get
        {
            return this.idRegimenFieldSpecified;
        }
        set
        {
            this.idRegimenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public int periodo
    {
        get
        {
            return this.periodoField;
        }
        set
        {
            this.periodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoSpecified
    {
        get
        {
            return this.periodoFieldSpecified;
        }
        set
        {
            this.periodoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string tipoRegimen
    {
        get
        {
            return this.tipoRegimenField;
        }
        set
        {
            this.tipoRegimenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class datosRegimenGeneral
{
    
    private actividad[] actividadField;
    
    private categoria categoriaAutonomoField;
    
    private impuesto[] impuestoField;
    
    private regimen[] regimenField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public actividad[] actividad
    {
        get
        {
            return this.actividadField;
        }
        set
        {
            this.actividadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public categoria categoriaAutonomo
    {
        get
        {
            return this.categoriaAutonomoField;
        }
        set
        {
            this.categoriaAutonomoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public impuesto[] impuesto
    {
        get
        {
            return this.impuestoField;
        }
        set
        {
            this.impuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regimen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public regimen[] regimen
    {
        get
        {
            return this.regimenField;
        }
        set
        {
            this.regimenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class actividad
{
    
    private string descripcionActividadField;
    
    private long idActividadField;
    
    private bool idActividadFieldSpecified;
    
    private int nomencladorField;
    
    private bool nomencladorFieldSpecified;
    
    private int ordenField;
    
    private bool ordenFieldSpecified;
    
    private int periodoField;
    
    private bool periodoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string descripcionActividad
    {
        get
        {
            return this.descripcionActividadField;
        }
        set
        {
            this.descripcionActividadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public long idActividad
    {
        get
        {
            return this.idActividadField;
        }
        set
        {
            this.idActividadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idActividadSpecified
    {
        get
        {
            return this.idActividadFieldSpecified;
        }
        set
        {
            this.idActividadFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int nomenclador
    {
        get
        {
            return this.nomencladorField;
        }
        set
        {
            this.nomencladorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nomencladorSpecified
    {
        get
        {
            return this.nomencladorFieldSpecified;
        }
        set
        {
            this.nomencladorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public int orden
    {
        get
        {
            return this.ordenField;
        }
        set
        {
            this.ordenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ordenSpecified
    {
        get
        {
            return this.ordenFieldSpecified;
        }
        set
        {
            this.ordenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public int periodo
    {
        get
        {
            return this.periodoField;
        }
        set
        {
            this.periodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoSpecified
    {
        get
        {
            return this.periodoFieldSpecified;
        }
        set
        {
            this.periodoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class categoria
{
    
    private string descripcionCategoriaField;
    
    private int idCategoriaField;
    
    private bool idCategoriaFieldSpecified;
    
    private int idImpuestoField;
    
    private bool idImpuestoFieldSpecified;
    
    private int periodoField;
    
    private bool periodoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string descripcionCategoria
    {
        get
        {
            return this.descripcionCategoriaField;
        }
        set
        {
            this.descripcionCategoriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int idCategoria
    {
        get
        {
            return this.idCategoriaField;
        }
        set
        {
            this.idCategoriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idCategoriaSpecified
    {
        get
        {
            return this.idCategoriaFieldSpecified;
        }
        set
        {
            this.idCategoriaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int idImpuesto
    {
        get
        {
            return this.idImpuestoField;
        }
        set
        {
            this.idImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idImpuestoSpecified
    {
        get
        {
            return this.idImpuestoFieldSpecified;
        }
        set
        {
            this.idImpuestoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public int periodo
    {
        get
        {
            return this.periodoField;
        }
        set
        {
            this.periodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoSpecified
    {
        get
        {
            return this.periodoFieldSpecified;
        }
        set
        {
            this.periodoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class impuesto
{
    
    private string descripcionImpuestoField;
    
    private int idImpuestoField;
    
    private bool idImpuestoFieldSpecified;
    
    private int periodoField;
    
    private bool periodoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string descripcionImpuesto
    {
        get
        {
            return this.descripcionImpuestoField;
        }
        set
        {
            this.descripcionImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int idImpuesto
    {
        get
        {
            return this.idImpuestoField;
        }
        set
        {
            this.idImpuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idImpuestoSpecified
    {
        get
        {
            return this.idImpuestoFieldSpecified;
        }
        set
        {
            this.idImpuestoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int periodo
    {
        get
        {
            return this.periodoField;
        }
        set
        {
            this.periodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoSpecified
    {
        get
        {
            return this.periodoFieldSpecified;
        }
        set
        {
            this.periodoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class relacion
{
    
    private string apellidoPersonaAsociadaField;
    
    private System.DateTime ffRelacionField;
    
    private bool ffRelacionFieldSpecified;
    
    private System.DateTime ffVencimientoField;
    
    private bool ffVencimientoFieldSpecified;
    
    private long idPersonaAsociadaField;
    
    private bool idPersonaAsociadaFieldSpecified;
    
    private string nombrePersonaAsociadaField;
    
    private string razonSocialPersonaAsociadaField;
    
    private string tipoComponenteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string apellidoPersonaAsociada
    {
        get
        {
            return this.apellidoPersonaAsociadaField;
        }
        set
        {
            this.apellidoPersonaAsociadaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public System.DateTime ffRelacion
    {
        get
        {
            return this.ffRelacionField;
        }
        set
        {
            this.ffRelacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ffRelacionSpecified
    {
        get
        {
            return this.ffRelacionFieldSpecified;
        }
        set
        {
            this.ffRelacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public System.DateTime ffVencimiento
    {
        get
        {
            return this.ffVencimientoField;
        }
        set
        {
            this.ffVencimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ffVencimientoSpecified
    {
        get
        {
            return this.ffVencimientoFieldSpecified;
        }
        set
        {
            this.ffVencimientoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public long idPersonaAsociada
    {
        get
        {
            return this.idPersonaAsociadaField;
        }
        set
        {
            this.idPersonaAsociadaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idPersonaAsociadaSpecified
    {
        get
        {
            return this.idPersonaAsociadaFieldSpecified;
        }
        set
        {
            this.idPersonaAsociadaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string nombrePersonaAsociada
    {
        get
        {
            return this.nombrePersonaAsociadaField;
        }
        set
        {
            this.nombrePersonaAsociadaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string razonSocialPersonaAsociada
    {
        get
        {
            return this.razonSocialPersonaAsociadaField;
        }
        set
        {
            this.razonSocialPersonaAsociadaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string tipoComponente
    {
        get
        {
            return this.tipoComponenteField;
        }
        set
        {
            this.tipoComponenteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class datosMonotributo
{
    
    private actividad[] actividadField;
    
    private actividad actividadMonotributistaField;
    
    private categoria categoriaMonotributoField;
    
    private relacion[] componenteDeSociedadField;
    
    private impuesto[] impuestoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public actividad[] actividad
    {
        get
        {
            return this.actividadField;
        }
        set
        {
            this.actividadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public actividad actividadMonotributista
    {
        get
        {
            return this.actividadMonotributistaField;
        }
        set
        {
            this.actividadMonotributistaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public categoria categoriaMonotributo
    {
        get
        {
            return this.categoriaMonotributoField;
        }
        set
        {
            this.categoriaMonotributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("componenteDeSociedad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public relacion[] componenteDeSociedad
    {
        get
        {
            return this.componenteDeSociedadField;
        }
        set
        {
            this.componenteDeSociedadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
    public impuesto[] impuesto
    {
        get
        {
            return this.impuestoField;
        }
        set
        {
            this.impuestoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class domicilio
{
    
    private string codPostalField;
    
    private string datoAdicionalField;
    
    private string descripcionProvinciaField;
    
    private string direccionField;
    
    private int idProvinciaField;
    
    private bool idProvinciaFieldSpecified;
    
    private string localidadField;
    
    private string tipoDatoAdicionalField;
    
    private string tipoDomicilioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string codPostal
    {
        get
        {
            return this.codPostalField;
        }
        set
        {
            this.codPostalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string datoAdicional
    {
        get
        {
            return this.datoAdicionalField;
        }
        set
        {
            this.datoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string descripcionProvincia
    {
        get
        {
            return this.descripcionProvinciaField;
        }
        set
        {
            this.descripcionProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string direccion
    {
        get
        {
            return this.direccionField;
        }
        set
        {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public int idProvincia
    {
        get
        {
            return this.idProvinciaField;
        }
        set
        {
            this.idProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idProvinciaSpecified
    {
        get
        {
            return this.idProvinciaFieldSpecified;
        }
        set
        {
            this.idProvinciaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string localidad
    {
        get
        {
            return this.localidadField;
        }
        set
        {
            this.localidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string tipoDatoAdicional
    {
        get
        {
            return this.tipoDatoAdicionalField;
        }
        set
        {
            this.tipoDatoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string tipoDomicilio
    {
        get
        {
            return this.tipoDomicilioField;
        }
        set
        {
            this.tipoDomicilioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class dependencia
{
    
    private string codPostalField;
    
    private string descripcionDependenciaField;
    
    private string descripcionProvinciaField;
    
    private string direccionField;
    
    private int idDependenciaField;
    
    private bool idDependenciaFieldSpecified;
    
    private int idProvinciaField;
    
    private bool idProvinciaFieldSpecified;
    
    private string localidadField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string codPostal
    {
        get
        {
            return this.codPostalField;
        }
        set
        {
            this.codPostalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string descripcionDependencia
    {
        get
        {
            return this.descripcionDependenciaField;
        }
        set
        {
            this.descripcionDependenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string descripcionProvincia
    {
        get
        {
            return this.descripcionProvinciaField;
        }
        set
        {
            this.descripcionProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string direccion
    {
        get
        {
            return this.direccionField;
        }
        set
        {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public int idDependencia
    {
        get
        {
            return this.idDependenciaField;
        }
        set
        {
            this.idDependenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idDependenciaSpecified
    {
        get
        {
            return this.idDependenciaFieldSpecified;
        }
        set
        {
            this.idDependenciaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public int idProvincia
    {
        get
        {
            return this.idProvinciaField;
        }
        set
        {
            this.idProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idProvinciaSpecified
    {
        get
        {
            return this.idProvinciaFieldSpecified;
        }
        set
        {
            this.idProvinciaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string localidad
    {
        get
        {
            return this.localidadField;
        }
        set
        {
            this.localidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class caracterizacion
{
    
    private string descripcionCaracterizacionField;
    
    private int idCaracterizacionField;
    
    private bool idCaracterizacionFieldSpecified;
    
    private int periodoField;
    
    private bool periodoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string descripcionCaracterizacion
    {
        get
        {
            return this.descripcionCaracterizacionField;
        }
        set
        {
            this.descripcionCaracterizacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int idCaracterizacion
    {
        get
        {
            return this.idCaracterizacionField;
        }
        set
        {
            this.idCaracterizacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idCaracterizacionSpecified
    {
        get
        {
            return this.idCaracterizacionFieldSpecified;
        }
        set
        {
            this.idCaracterizacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int periodo
    {
        get
        {
            return this.periodoField;
        }
        set
        {
            this.periodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoSpecified
    {
        get
        {
            return this.periodoFieldSpecified;
        }
        set
        {
            this.periodoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class datosGenerales
{
    
    private string apellidoField;
    
    private caracterizacion[] caracterizacionField;
    
    private dependencia dependenciaField;
    
    private domicilio domicilioFiscalField;
    
    private string estadoClaveField;
    
    private System.DateTime fechaContratoSocialField;
    
    private bool fechaContratoSocialFieldSpecified;
    
    private System.DateTime fechaFallecimientoField;
    
    private bool fechaFallecimientoFieldSpecified;
    
    private long idPersonaField;
    
    private bool idPersonaFieldSpecified;
    
    private int mesCierreField;
    
    private bool mesCierreFieldSpecified;
    
    private string nombreField;
    
    private string razonSocialField;
    
    private string tipoClaveField;
    
    private string tipoPersonaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string apellido
    {
        get
        {
            return this.apellidoField;
        }
        set
        {
            this.apellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("caracterizacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public caracterizacion[] caracterizacion
    {
        get
        {
            return this.caracterizacionField;
        }
        set
        {
            this.caracterizacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public dependencia dependencia
    {
        get
        {
            return this.dependenciaField;
        }
        set
        {
            this.dependenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public domicilio domicilioFiscal
    {
        get
        {
            return this.domicilioFiscalField;
        }
        set
        {
            this.domicilioFiscalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string estadoClave
    {
        get
        {
            return this.estadoClaveField;
        }
        set
        {
            this.estadoClaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public System.DateTime fechaContratoSocial
    {
        get
        {
            return this.fechaContratoSocialField;
        }
        set
        {
            this.fechaContratoSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaContratoSocialSpecified
    {
        get
        {
            return this.fechaContratoSocialFieldSpecified;
        }
        set
        {
            this.fechaContratoSocialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public System.DateTime fechaFallecimiento
    {
        get
        {
            return this.fechaFallecimientoField;
        }
        set
        {
            this.fechaFallecimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaFallecimientoSpecified
    {
        get
        {
            return this.fechaFallecimientoFieldSpecified;
        }
        set
        {
            this.fechaFallecimientoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public long idPersona
    {
        get
        {
            return this.idPersonaField;
        }
        set
        {
            this.idPersonaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idPersonaSpecified
    {
        get
        {
            return this.idPersonaFieldSpecified;
        }
        set
        {
            this.idPersonaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public int mesCierre
    {
        get
        {
            return this.mesCierreField;
        }
        set
        {
            this.mesCierreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mesCierreSpecified
    {
        get
        {
            return this.mesCierreFieldSpecified;
        }
        set
        {
            this.mesCierreFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string nombre
    {
        get
        {
            return this.nombreField;
        }
        set
        {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string razonSocial
    {
        get
        {
            return this.razonSocialField;
        }
        set
        {
            this.razonSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string tipoClave
    {
        get
        {
            return this.tipoClaveField;
        }
        set
        {
            this.tipoClaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string tipoPersona
    {
        get
        {
            return this.tipoPersonaField;
        }
        set
        {
            this.tipoPersonaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class personaReturn
{
    
    private datosGenerales datosGeneralesField;
    
    private datosMonotributo datosMonotributoField;
    
    private datosRegimenGeneral datosRegimenGeneralField;
    
    private errorConstancia errorConstanciaField;
    
    private errorMonotributo errorMonotributoField;
    
    private errorRegimenGeneral errorRegimenGeneralField;
    
    private metadata metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public datosGenerales datosGenerales
    {
        get
        {
            return this.datosGeneralesField;
        }
        set
        {
            this.datosGeneralesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public datosMonotributo datosMonotributo
    {
        get
        {
            return this.datosMonotributoField;
        }
        set
        {
            this.datosMonotributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public datosRegimenGeneral datosRegimenGeneral
    {
        get
        {
            return this.datosRegimenGeneralField;
        }
        set
        {
            this.datosRegimenGeneralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public errorConstancia errorConstancia
    {
        get
        {
            return this.errorConstanciaField;
        }
        set
        {
            this.errorConstanciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public errorMonotributo errorMonotributo
    {
        get
        {
            return this.errorMonotributoField;
        }
        set
        {
            this.errorMonotributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public errorRegimenGeneral errorRegimenGeneral
    {
        get
        {
            return this.errorRegimenGeneralField;
        }
        set
        {
            this.errorRegimenGeneralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public metadata metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", ConfigurationName="AfipConstanciaInscripcion.PersonaServiceA5")]
public interface PersonaServiceA5
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(AfipConstanciaInscripcion.SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaResponse> getPersonaAsync(AfipConstanciaInscripcion.getPersona request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(AfipConstanciaInscripcion.SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaListResponse> getPersonaListAsync(AfipConstanciaInscripcion.getPersonaList request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(AfipConstanciaInscripcion.SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersona_v2Response> getPersona_v2Async(AfipConstanciaInscripcion.getPersona_v2 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AfipConstanciaInscripcion.dummyResponse> dummyAsync(AfipConstanciaInscripcion.dummy request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(AfipConstanciaInscripcion.SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaList_v2Response> getPersonaList_v2Async(AfipConstanciaInscripcion.getPersonaList_v2 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersona", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersona
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idPersona;
    
    public getPersona()
    {
    }
    
    public getPersona(string token, string sign, long cuitRepresentada, long idPersona)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.idPersona = idPersona;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AfipConstanciaInscripcion.personaReturn personaReturn;
    
    public getPersonaResponse()
    {
    }

    public getPersonaResponse(AfipConstanciaInscripcion.personaReturn personaReturn) => this.personaReturn = personaReturn;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class personaListReturn
{
    
    private metadata metadataField;
    
    private persona[] personaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public metadata metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public persona[] persona
    {
        get
        {
            return this.personaField;
        }
        set
        {
            this.personaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class persona
{
    
    private datosGenerales datosGeneralesField;
    
    private datosMonotributo datosMonotributoField;
    
    private datosRegimenGeneral datosRegimenGeneralField;
    
    private errorConstancia errorConstanciaField;
    
    private errorMonotributo errorMonotributoField;
    
    private errorRegimenGeneral errorRegimenGeneralField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public datosGenerales datosGenerales
    {
        get
        {
            return this.datosGeneralesField;
        }
        set
        {
            this.datosGeneralesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public datosMonotributo datosMonotributo
    {
        get
        {
            return this.datosMonotributoField;
        }
        set
        {
            this.datosMonotributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public datosRegimenGeneral datosRegimenGeneral
    {
        get
        {
            return this.datosRegimenGeneralField;
        }
        set
        {
            this.datosRegimenGeneralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public errorConstancia errorConstancia
    {
        get
        {
            return this.errorConstanciaField;
        }
        set
        {
            this.errorConstanciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public errorMonotributo errorMonotributo
    {
        get
        {
            return this.errorMonotributoField;
        }
        set
        {
            this.errorMonotributoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public errorRegimenGeneral errorRegimenGeneral
    {
        get
        {
            return this.errorRegimenGeneralField;
        }
        set
        {
            this.errorRegimenGeneralField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaList
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long[] idPersona;
    
    public getPersonaList()
    {
    }
    
    public getPersonaList(string token, string sign, long cuitRepresentada, long[] idPersona)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.idPersona = idPersona;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaListResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaListResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AfipConstanciaInscripcion.personaListReturn personaListReturn;
    
    public getPersonaListResponse()
    {
    }

    public getPersonaListResponse(AfipConstanciaInscripcion.personaListReturn personaListReturn) => this.personaListReturn = personaListReturn;
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersona_v2", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersona_v2
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idPersona;
    
    public getPersona_v2()
    {
    }
    
    public getPersona_v2(string token, string sign, long cuitRepresentada, long idPersona)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.idPersona = idPersona;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersona_v2Response", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersona_v2Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AfipConstanciaInscripcion.personaReturn personaReturn;
    
    public getPersona_v2Response()
    {
    }

    public getPersona_v2Response(AfipConstanciaInscripcion.personaReturn personaReturn) => this.personaReturn = personaReturn;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
public partial class dummyReturn
{
    
    private string appserverField;
    
    private string authserverField;
    
    private string dbserverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string appserver
    {
        get
        {
            return this.appserverField;
        }
        set
        {
            this.appserverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string authserver
    {
        get
        {
            return this.authserverField;
        }
        set
        {
            this.authserverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string dbserver
    {
        get
        {
            return this.dbserverField;
        }
        set
        {
            this.dbserverField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="dummy", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class dummy
{
    
    public dummy()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="dummyResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class dummyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AfipConstanciaInscripcion.dummyReturn @return;
    
    public dummyResponse()
    {
    }

    public dummyResponse(AfipConstanciaInscripcion.dummyReturn @return) => this.@return = @return;
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList_v2", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaList_v2
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long[] idPersona;
    
    public getPersonaList_v2()
    {
    }
    
    public getPersonaList_v2(string token, string sign, long cuitRepresentada, long[] idPersona)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.idPersona = idPersona;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList_v2Response", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaList_v2Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AfipConstanciaInscripcion.personaListReturn personaListReturn;
    
    public getPersonaList_v2Response()
    {
    }

    public getPersonaList_v2Response(AfipConstanciaInscripcion.personaListReturn personaListReturn) => this.personaListReturn = personaListReturn;
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public interface PersonaServiceA5Channel : AfipConstanciaInscripcion.PersonaServiceA5, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public partial class PersonaServiceA5Client : System.ServiceModel.ClientBase<AfipConstanciaInscripcion.PersonaServiceA5>, AfipConstanciaInscripcion.PersonaServiceA5
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public PersonaServiceA5Client() : 
            base(PersonaServiceA5Client.GetDefaultBinding(), PersonaServiceA5Client.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.PersonaServiceA5Port.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA5Client(EndpointConfiguration endpointConfiguration) : 
            base(PersonaServiceA5Client.GetBindingForEndpoint(endpointConfiguration), PersonaServiceA5Client.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA5Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(PersonaServiceA5Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA5Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(PersonaServiceA5Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaResponse> getPersonaAsync(AfipConstanciaInscripcion.getPersona request)
    {
        return base.Channel.getPersonaAsync(request);
    }
    
    public System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaListResponse> getPersonaListAsync(AfipConstanciaInscripcion.getPersonaList request)
    {
        return base.Channel.getPersonaListAsync(request);
    }
    
    public System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersona_v2Response> getPersona_v2Async(AfipConstanciaInscripcion.getPersona_v2 request)
    {
        return base.Channel.getPersona_v2Async(request);
    }
    
    public System.Threading.Tasks.Task<AfipConstanciaInscripcion.dummyResponse> dummyAsync(AfipConstanciaInscripcion.dummy request)
    {
        return base.Channel.dummyAsync(request);
    }
    
    public System.Threading.Tasks.Task<AfipConstanciaInscripcion.getPersonaList_v2Response> getPersonaList_v2Async(AfipConstanciaInscripcion.getPersonaList_v2 request)
    {
        return base.Channel.getPersonaList_v2Async(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PersonaServiceA5Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PersonaServiceA5Port))
        {
            return new System.ServiceModel.EndpointAddress("https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return PersonaServiceA5Client.GetBindingForEndpoint(EndpointConfiguration.PersonaServiceA5Port);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return PersonaServiceA5Client.GetEndpointAddress(EndpointConfiguration.PersonaServiceA5Port);
    }
    
    public enum EndpointConfiguration
    {
        
        PersonaServiceA5Port,
    }
}
